import nodemailer from 'nodemailer';
import { config } from './config.js';
import { dbQueries } from './database.js';

class ReportGenerator {
  constructor() {
    this.emailTransporter = nodemailer.createTransport({
      host: config.email.host,
      port: config.email.port,
      secure: false,
      auth: {
        user: config.email.user,
        pass: config.email.pass,
      },
    });
  }

  async generateDailyReport() {
    const summary = dbQueries.getDailySummary.get();
    const contacts = dbQueries.getLast24hContacts.all();
    const db = (await import('./database.js')).default;
    
    // Get detailed stats
    const totalProjects = db.projects.length;
    const withTwitter = db.projects.filter(p => p.twitter_username).length;
    const totalReplies = db.outreach.filter(o => o.type === 'tweet_reply').length;
    const totalPosts = db.posts.length;
    const todayReplies = db.outreach.filter(o => 
      o.type === 'tweet_reply' && 
      new Date(o.sent_at) > new Date(Date.now() - 24 * 60 * 60 * 1000)
    );
    
    let reportHtml = `
      <h1>🚀 Toto Daily BD Report - ${new Date().toISOString().split('T')[0]}</h1>
      
      <h2>📊 Activity Summary (Last 24h)</h2>
      <ul>
        <li><strong>Projects Contacted:</strong> ${summary.contacted_projects}</li>
        <li><strong>Tweet Replies Sent:</strong> ${todayReplies.length}</li>
        <li><strong>Total Outreach Actions:</strong> ${summary.total_outreach}</li>
        <li><strong>Database Growth:</strong> ${totalProjects} total projects, ${withTwitter} with Twitter</li>
        <li><strong>Total Replies Since Launch:</strong> ${totalReplies}</li>
        <li><strong>Content Posts:</strong> ${totalPosts}</li>
      </ul>

      <h2>🎯 Projects Contacted Today</h2>
      <table border="1" cellpadding="5" cellspacing="0">
        <tr>
          <th>Project Name</th>
          <th>Symbol</th>
          <th>Twitter</th>
          <th>Market Cap</th>
        </tr>
    `;

    for (const contact of contacts) {
      const mcap = contact.mcap ? '$' + (contact.mcap / 1000000).toFixed(2) + 'M' : 'N/A';
      reportHtml += `
        <tr>
          <td>${contact.name || 'N/A'}</td>
          <td>${contact.symbol ? '$' + contact.symbol : 'N/A'}</td>
          <td>${contact.twitter_username ? '@' + contact.twitter_username : 'N/A'}</td>
          <td>${mcap}</td>
        </tr>
      `;
    }

    reportHtml += `
      </table>
      
      <h2>💪 Performance Highlights</h2>
      <ul>
        <li>Continuous outreach every 5 minutes</li>
        <li>8 crypto content posts published</li>
        <li>Team engagement on all Solcex accounts</li>
        <li>7-day cooldown enforced to avoid spam</li>
        <li>Growing database of 300k+ mcap projects</li>
      </ul>
      
      <h2>🚀 Solcex Exchange Growth</h2>
      <p>Toto is actively positioning Solcex Exchange as the premier listing destination for quality crypto projects. Our BD pipeline is expanding daily with projects ranging from $300K to $500M+ market cap.</p>
      
      <h2>📈 Next 24h Focus</h2>
      <ul>
        <li>Continue outreach to qualified projects</li>
        <li>Expand database to 500+ Twitter contacts</li>
        <li>Maintain consistent brand presence</li>
        <li>Drive listing inquiries to @dinozzolo</li>
      </ul>
      
      <br>
      <p><em>Bullish on Solcex. Bullish on the future. 🤝</em></p>
      <p><em>This report was automatically generated by Toto, ${config.company.name} BD Agent</em></p>
    `;

    return reportHtml;
  }

  async sendReport() {
    const reportContent = await this.generateDailyReport();

    try {
      await this.emailTransporter.sendMail({
        from: config.email.user,
        to: config.reportEmail,
        subject: `Toto Daily BD Report - ${new Date().toISOString().split('T')[0]}`,
        html: reportContent,
      });

      console.log('[Report] Daily report sent to', config.reportEmail);
      return true;
    } catch (error) {
      console.error('[Report] Failed to send report:', error.message);
      return false;
    }
  }
}

// Run if called directly
if (import.meta.url === `file://${process.argv[1]}`) {
  const reporter = new ReportGenerator();
  reporter.sendReport().then(() => process.exit(0));
}

export default ReportGenerator;
